name: Vinit Kumar
description: >
    Vinit Kumar
about: >
    Vinit is a Senior Engineer at Socialschools B.V. His expertise lies in writing scalable backend systems in Python, Django, Golang, Node.js and React. He occasionally dabbles with iOS and Android development too.

    He enjoys solving difficult problems, debugging and coming up with simple solutions that just works.

    At Socialschools, he has worked on APIs, performance, scaling and security of the complete application. With over 5 years of experience in Python/Django, he is able to rapidly build features and debug nasty bugs.

master_repo: false
url: "https://vinitkumar.me"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 5

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Vinit Kumar
  avatar:         "https://avatars1.githubusercontent.com/u/537678?s=120&v=4"
  email:          "vinit1414.08@bitmesra.ac.in"
  # Social networking links used in footer. Update and remove as you like.
  twitter: https://twitter.com/vinitkme
  github: https://github.com/vinitkumar
  stackexchange: https://stackoverflow.com/users/859112/vinit-kumar?tab=profile
  linkedin: https://www.linkedin.com/in/vinitatlinkedin
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-40854387-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
